from custom_components.opcua.const import NODE_KIND_SENSOR, NODE_KIND_BINARY_SENSOR, NODE_KIND_SWITCH, NODE_KIND_LIGHT, NODE_KIND_BUTTON, NODE_KIND_CLIMATE, NODE_KIND_COVER, NODE_KIND_DATE, NODE_KIND_DATETIME, NODE_KIND_FAN, NODE_KIND_NOTIFY, NODE_KIND_NUMBER, NODE_KIND_SCENE, NODE_KIND_SELECT, NODE_KIND_TEXT, NODE_KIND_TIME, NODE_KIND_WEATHER

def test_all_entity_kinds_defined_for_options_flow():
    kinds={NODE_KIND_SENSOR,NODE_KIND_BINARY_SENSOR,NODE_KIND_SWITCH,NODE_KIND_LIGHT,NODE_KIND_BUTTON,NODE_KIND_CLIMATE,NODE_KIND_COVER,NODE_KIND_DATE,NODE_KIND_DATETIME,NODE_KIND_FAN,NODE_KIND_NOTIFY,NODE_KIND_NUMBER,NODE_KIND_SCENE,NODE_KIND_SELECT,NODE_KIND_TEXT,NODE_KIND_TIME,NODE_KIND_WEATHER}
    assert len(kinds)==17
